FORMAT: 1A

# BuddyPress JS API
An experiment with wireframing and mocking a JS (REST) API for BuddyPress. Any eventual API for BuddyPress will be implemented using [WP-API](https://github.com/WP-API/WP-API). Want to contribute? [Say hi on Github](https://github.com/paulgibbs/bp-tomorrowland).

# Group Activity
The Activity component provides global, personal, and group activity streams with threaded commenting, direct posting, favoriting, and @mentions, all with full RSS feed and email notification support.

## Activities [/activity{?count_total,date_query,display_comments,exclude,in,max,meta_query,page,per_page,show_hidden,search_terms,sort,spam,update_meta_cache}]
### List all Activities [GET]

+ Parameters
    + count_total = `false` (optional, bool) ... If true, an additional DB query is run to count the total activity items for the query.
    + date_query = `array` (optional, array) ... Filter by date. See first parameter of `WP_Date_Query` for format.
    + display_comments = `false` (optional, bool|string) ... Whether to return comments.
        + Values
            + `false` No comments.
            + `"stream"` Show comments within the activity stream.
            + `"threaded"` Show comments threaded below the related activity item.
    + exclude  (optional, string) ... Comma-separated list of activity IDs to exclude from results.
    + in  (optional, string) ...  Comma-separated list of activity IDs to include in results.
    + max = `0` (optional, integer) ... Maximum number of results to return (defaults to unlimited).
    + meta_query = `array` (optional, array) ... Filter by activity meta. See `WP_Meta_Query` for format.
    + page = `1` (optional, integer) ... The page of results to get. Used for pagination.
    + per_page = `25` (optional, integer) ... Results per page.
    + show_hidden = `false` (optional, bool) ... Whether to show activity items that are hidden site-wide.
    + search_terms (optional, string) ... Search for activities matching this value.
    + sort = `"DESC"` (optional, string) ... Sorts results by timestamp, in this order.
        + Values
            + `"ASC"`
            + `"DESC"`
    + spam = `"ham_only"` (optional, string) ... Whether to fetch activity items that have been marked as spam.
        + Values
            + `"all"` Ham and spam.
            + `"ham_only"` No spam.
            + `"spam_only"` Only spam.
    + update_meta_cache = `true` (optional, bool) ... Whether to pre-fetch metadata for queried activity items.

+ Response 200 (application/json)

        [{
        "action": "<a href='http://example.com/members/admin/profile/'>admin</a>&#8217;s posted an update",
        "component": "xprofile",
        "content": "BuddyPress is awesome!",
        "date_recorded": "2014-08-10 16:54:37",
        "display_name": "admin",
        "hide_sitewide": 0,
        "id": 554,
        "is_spam": 0,
        "item_id": 0,
        "mptt_left": 0,
        "mptt_right": 0,
        "secondary_item_id": 0,
        "primary_link": "http://example.com/members/admin/profile/",
        "type": "activity_update",
        "user_email": "example@example.com",
        "user_fullname": "admin",
        "user_id": 1,
        "user_login": "admin",
        "user_nicename": "admin"
        }]

## Activities [/activity]

### Create Activity [POST]

+ Parameters
    + action = `""` (optional, string) ... The activity name. Only used if the internal activity type's `format_callback` handler is missing (e.g. when the owning component is disabled).
    + content = `""` (optional, string) ... The activity content.
    + component (string) ... The name of the component associated with the activity item.
        + Values
            + `"activity"`
            + `"blogs"`
            + `"friends"`
            + `"groups"`
            + `"members"`
            + `"messages"`
            + `"notifications"`
            + `"settings"`
            + `"xprofile"`
    + date_recorded = `now` (optional, string) ... The GMT timestamp of when the activity item was recorded, in `Y-m-d h:i:s` format.
    + hide_sitewide = `false` (optional, bool) ... Should the activity item be hidden on sitewide streams?
    + is_spam = `false` (optional, bool) ... Should the activity item be marked as spam?
    + item_id = `0` (optional, integer) ... The ID of the associated item. Depends on the activity `type`.
    + primary_link = `""` (optional, string) ... The permalink to the thing that this activity item is about.
    + secondary_item_id = `0` (optional, integer) ... The ID of a secondary associated item. Depends on the activity `type`.
    + type (string) ... The type of this activity (e.g. activity_update TODO).
    + user_id = `current user's ID` (optional, integer) ... The ID of the user associated with this activity item. Can be left unset if the item is not related to a specific user.

+ Request (application/json)
    + Body

            {
            "content": "BuddyPress is awesome!",
            "primary_link": "http://example.com/activity/p/554",
            "component": "activity",
            "type": "activity_update"
            }

+ Response 201 (application/json)

    + Headers

            Location: /activity/123

## Activity [/activity/{id}]
A single Activity object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve Activity [GET]
+ Response 200 (application/json)

    + Headers

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

+ Response 404 (application/json)

### Update Activity [POST]
+ Response 201 (application/json)

    + Headers

            Location: http://example.com/new_thing.html

+ Response 404 (application/json)

### Remove Activity [DELETE]
+ Response 200 (application/json)

+ Response 404 (application/json)


# Group xProfile
The xProfile component allows you to customise your community with fully editable profile fields that allow your users to describe themselves.